apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: ocp-registry.kscada.kdneri.com:5000/olm-redhat/redhat/redhat-operator-index:v4.20
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 20m
